<div class="news">
  <h1>Lorem dolor sit amet consectetur adipiscing elit.</h1>

  <p>Lorem ipsum Veniam laboris nulla aliquip dolor anim Duis consectetur Ut anim veniam dolore quis dolor Ut nostrud qui consectetur dolor qui eiusmod do in id eu voluptate sunt id ut dolor irure do officia qui adipisicing voluptate laboris ad aute aliquip amet eiusmod ut deserunt laborum sunt officia ullamco nisi et in et do consectetur ex ut do ad ut sunt ea dolor aliqua labore elit fugiat irure laboris irure est ea fugiat enim cillum mollit Ut qui magna mollit sint sit ullamco officia aute ut do cupidatat nostrud sed esse reprehenderit nostrud adipisicing labore in proident qui eiusmod incididunt quis quis voluptate velit reprehenderit deserunt adipisicing et dolore ut labore dolor in irure ea dolor aliquip aute adipisicing consequat mollit non sunt labore in labore elit aliquip minim sed esse exercitation occaecat reprehenderit veniam.</p>

  <img src="<?= base_url() . 'assets/images/sample-project.jpg'; ?>" />

  <p>Lorem ipsum Veniam laboris nulla aliquip dolor anim Duis consectetur Ut anim veniam dolore quis dolor Ut nostrud qui consectetur dolor qui eiusmod do in id eu voluptate sunt id ut dolor irure do officia qui adipisicing voluptate laboris ad aute aliquip amet eiusmod ut deserunt laborum sunt officia ullamco nisi et in et do consectetur ex ut do ad ut sunt ea dolor aliqua labore elit fugiat irure laboris irure est ea fugiat enim cillum mollit Ut qui magna mollit sint sit ullamco officia aute ut do cupidatat nostrud sed esse reprehenderit nostrud adipisicing labore in proident qui eiusmod incididunt quis quis voluptate velit reprehenderit deserunt adipisicing et dolore ut labore dolor in irure ea dolor aliquip aute adipisicing consequat mollit non sunt labore in labore elit aliquip minim sed esse exercitation occaecat reprehenderit veniam. Lorem ipsum Laboris qui sint qui veniam consectetur nisi eiusmod Excepteur sunt aliqua nostrud in exercitation nostrud laborum sit anim ad sunt eu quis esse commodo proident nostrud sint magna exercitation pariatur do eiusmod ullamco cupidatat velit id esse reprehenderit non minim irure aliqua dolor Duis elit ullamco nisi sint consectetur tempor ut laboris et esse voluptate quis non consectetur nisi veniam cupidatat anim labore velit eu pariatur anim veniam magna irure in ex nostrud cillum ullamco est in dolore esse dolor ea reprehenderit laboris nisi officia enim aute sint elit Excepteur dolore dolore ex ullamco cupidatat sit incididunt ex cillum in quis labore incididunt nisi commodo nulla adipisicing non proident Duis esse esse cupidatat in labore consequat labore aliqua dolore magna magna exercitation dolore dolore incididunt tempor dolore ad laborum anim fugiat laborum elit eiusmod nisi laboris ex et Excepteur enim cupidatat et do in exercitation laboris non anim do proident culpa deserunt in ea magna ut qui ad laborum velit ex ex ex tempor esse velit sed eiusmod ut magna irure non ea cillum amet minim ad Ut voluptate id non Duis non et eiusmod sed enim exercitation qui in aliqua cupidatat eu dolore pariatur eu anim do elit veniam ut ullamco consectetur mollit incididunt ut quis qui esse commodo mollit ullamco aliqua eiusmod in sed ullamco magna est consectetur voluptate non irure sed sunt aliquip irure sit et mollit ut sunt do elit Duis est sit sed quis amet consequat commodo in reprehenderit irure qui exercitation.</p>

  <p>Lorem ipsum Veniam laboris nulla aliquip dolor anim Duis consectetur Ut anim veniam dolore quis dolor Ut nostrud qui consectetur dolor qui eiusmod do in id eu voluptate sunt id ut dolor irure do officia qui adipisicing voluptate laboris ad aute aliquip amet eiusmod ut deserunt laborum sunt officia ullamco nisi et in et do consectetur ex ut do ad ut sunt ea dolor aliqua labore elit fugiat irure laboris irure est ea fugiat enim cillum mollit Ut qui magna mollit sint sit ullamco officia aute ut do cupidatat nostrud sed esse reprehenderit nostrud adipisicing labore in proident qui eiusmod incididunt quis quis voluptate velit reprehenderit deserunt adipisicing et dolore ut labore dolor in irure ea dolor aliquip aute adipisicing consequat mollit non sunt labore in labore elit aliquip minim sed esse exercitation occaecat reprehenderit veniam.</p>
</div>