<div class="academic_programs">
  <input type="hidden" name="program" id="program" value="<?=$program?>">  
  <div class="program" id="ap-bachelor-of-science">
    <h1>Bachelor of Science</h1>
    <div class="field">
      <h2>Admission</h2>
      <p>Lorem ipsum Dolor aliquip cupidatat in proident consequat ut ea irure voluptate elit Excepteur pariatur pariatur sunt adipisicing aliqua cillum aute dolore consectetur voluptate sit Ut quis Ut commodo in dolore sunt ut sed sit fugiat dolor et enim dolor tempor cillum consectetur dolore anim adipisicing est occaecat qui voluptate dolore minim do reprehenderit irure ut sint cupidatat nulla tempor quis non cupidatat proident deserunt officia labore fugiat in voluptate Duis pariatur est Duis Duis pariatur laboris dolor do Ut nostrud laboris adipisicing ullamco Ut dolore nulla cillum non Ut sit commodo Duis exercitation sint magna nulla proident Excepteur ut tempor eu tempor ut enim consequat enim id in est in cillum anim in fugiat dolore cupidatat Ut aliquip deserunt esse Duis ex est dolor elit sit laborum adipisicing aliqua dolore ullamco irure deserunt elit in aliqua ad proident magna nisi ex amet irure nisi Excepteur exercitation reprehenderit deserunt velit consequat aliquip eiusmod reprehenderit dolor veniam eiusmod officia culpa mollit dolor occaecat sint cupidatat ad laborum ut voluptate elit voluptate laborum ex ut dolor anim dolore deserunt nulla mollit aute sit Ut Duis sed ut enim minim eu commodo do deserunt Excepteur sit est elit Ut cillum tempor consectetur nisi amet Ut magna ullamco reprehenderit cillum Ut aute sit dolor Ut nisi ex consequat laboris nulla dolor ex officia ex irure do in ullamco ea Excepteur esse esse in culpa sed labore esse sed consequat fugiat consectetur amet anim eu elit in Duis consectetur enim consectetur sint pariatur est reprehenderit eiusmod eu est Excepteur enim esse dolore reprehenderit nisi.Lorem ipsum Ex fugiat eiusmod Duis officia nulla incididunt aliquip minim officia incididunt aliquip do voluptate laboris Ut nostrud amet enim tempor.</p>
    </div>
    <div class="field">
      <h2>Rules</h2>
      <p>Lorem ipsum Ex fugiat eiusmod Duis officia nulla incididunt aliquip minim officia incididunt aliquip do voluptate laboris Ut nostrud amet enim tempor. Lorem ipsum Duis ex est officia quis do ut nostrud aliqua in ad in nostrud cupidatat do Duis non laboris sint in in mollit ea Ut commodo ea qui do officia sed voluptate mollit commodo deserunt labore nostrud nulla ullamco qui dolor fugiat tempor dolor velit commodo laboris sit ad ut sit exercitation sed id tempor et in incididunt in voluptate ea id consequat laborum esse Ut enim minim nulla labore anim mollit commodo labore velit Excepteur eiusmod nostrud incididunt esse eu labore exercitation reprehenderit irure eu tempor non eu Excepteur sint qui Duis id magna laborum amet ut commodo et reprehenderit tempor in ad reprehenderit amet incididunt consequat qui magna amet commodo Duis deserunt eiusmod dolor sit mollit consequat elit adipisicing tempor sed sunt do nisi deserunt sit nulla mollit quis in nulla laboris nulla cillum consequat commodo velit amet dolor in.</p>
    </div>
  </div>
  <div class="program" id="ap-master-of-science">
    <h1>Master of Science</h1>
    <div class="field">
      <h2>Admission</h2>
      <p>Lorem ipsum Minim ut fugiat ex laborum in veniam eu enim in commodo anim Excepteur ea elit esse eu sunt ex in culpa eiusmod nulla sed reprehenderit in adipisicing cupidatat anim velit cillum officia ullamco enim est amet laborum ut cillum Duis occaecat ex voluptate amet aute adipisicing mollit aute ullamco qui do proident tempor dolore ex ea ea officia exercitation sit nulla in minim reprehenderit adipisicing labore nisi sed nisi cillum in pariatur occaecat magna id minim qui culpa qui cupidatat deserunt ut in occaecat velit ut aute non sed quis tempor cupidatat deserunt laborum dolor do qui elit nostrud do ut nulla aliquip qui cillum sed ex occaecat dolor ut Ut enim proident ut ea ut laboris qui labore in sint laborum non do et dolor in et quis sit tempor exercitation pariatur est incididunt nulla enim exercitation culpa do irure reprehenderit nulla id nulla eiusmod pariatur dolore enim minim dolore qui deserunt laboris id tempor incididunt ad voluptate ut esse laboris.Lorem ipsum Ex fugiat eiusmod Duis officia nulla incididunt aliquip minim officia incididunt aliquip do voluptate laboris Ut nostrud amet enim tempor.</p>
    </div>
    <div class="field">
      <h2>Rules</h2>
      <p>Lorem ipsum Ad occaecat ut labore mollit adipisicing qui amet ex esse dolore dolor sunt cupidatat ut amet incididunt in in laboris Excepteur sunt sunt sed Excepteur aliquip sint ad ut ut eiusmod in proident dolor consequat velit id fugiat dolore nulla ut est tempor voluptate aliquip sed in in sit irure culpa qui sit ut est Ut commodo ex est adipisicing aliqua pariatur sed non aute ea magna cupidatat consectetur sit reprehenderit fugiat officia sit velit in magna in ut eiusmod Ut adipisicing elit ut tempor Duis amet in aliquip in pariatur exercitation incididunt incididunt ea exercitation consectetur aliqua est eiusmod in quis cupidatat aliquip ullamco ut ea occaecat qui enim fugiat minim sint in officia est nisi nulla dolore labore sint cupidatat voluptate eiusmod nulla in adipisicing laboris commodo amet velit laborum nisi esse sunt consequat non ea in nulla sed minim aliqua Ut velit nisi enim officia et non voluptate sunt in magna proident minim consequat enim dolor tempor nisi et officia deserunt ullamco voluptate consequat est est laboris elit nostrud enim nisi magna esse eu Ut irure laboris eiusmod amet cupidatat quis cillum exercitation proident minim elit nisi incididunt fugiat pariatur ex consequat deserunt deserunt Ut aliqua Ut consectetur exercitation eiusmod eu in in do.Lorem ipsum Ex fugiat eiusmod Duis officia nulla incididunt aliquip minim officia incididunt aliquip do voluptate laboris Ut nostrud amet enim tempor.</p>
    </div>
  </div>
  <div class="program" id="ap-continuing-education-program">
    <h1>Continuing Education Program</h1>
    <div class="field">
      <h2>Admission</h2>
      <p>Lorem ipsum Minim ut fugiat ex laborum in veniam eu enim in commodo anim Excepteur ea elit esse eu sunt ex in culpa eiusmod nulla sed reprehenderit in adipisicing cupidatat anim velit cillum officia ullamco enim est amet laborum ut cillum Duis occaecat ex voluptate amet aute adipisicing mollit aute ullamco qui do proident tempor dolore ex ea ea officia exercitation sit nulla in minim reprehenderit adipisicing labore nisi sed nisi cillum in pariatur occaecat magna id minim qui culpa qui cupidatat deserunt ut in occaecat velit ut aute non sed quis tempor cupidatat deserunt laborum dolor do qui elit nostrud do ut nulla aliquip qui cillum sed ex occaecat dolor ut Ut enim proident ut ea ut laboris qui labore in sint laborum non do et dolor in et quis sit tempor exercitation pariatur est incididunt nulla enim exercitation culpa do irure reprehenderit nulla id nulla eiusmod pariatur dolore enim minim dolore qui deserunt laboris id tempor incididunt ad voluptate ut esse laboris.Lorem ipsum Ex fugiat eiusmod Duis officia nulla incididunt aliquip minim officia incididunt aliquip do voluptate laboris Ut nostrud amet enim tempor.</p>
    </div>
    <div class="field">
      <h2>Rules</h2>
      <p>Lorem ipsum Ad occaecat ut labore mollit adipisicing qui amet ex esse dolore dolor sunt cupidatat ut amet incididunt in in laboris Excepteur sunt sunt sed Excepteur aliquip sint ad ut ut eiusmod in proident dolor consequat velit id fugiat dolore nulla ut est tempor voluptate aliquip sed in in sit irure culpa qui sit ut est Ut commodo ex est adipisicing aliqua pariatur sed non aute ea magna cupidatat consectetur sit reprehenderit fugiat officia sit velit in magna in ut eiusmod Ut adipisicing elit ut tempor Duis amet in aliquip in pariatur exercitation incididunt incididunt ea exercitation consectetur aliqua est eiusmod in quis cupidatat aliquip ullamco ut ea occaecat qui enim fugiat minim sint in officia est nisi nulla dolore labore sint cupidatat voluptate eiusmod nulla in adipisicing laboris commodo amet velit laborum nisi esse sunt consequat non ea in nulla sed minim aliqua Ut velit nisi enim officia et non voluptate sunt in magna proident minim consequat enim dolor tempor nisi et officia deserunt ullamco voluptate consequat est est laboris elit nostrud enim nisi magna esse eu Ut irure laboris eiusmod amet cupidatat quis cillum exercitation proident minim elit nisi incididunt fugiat pariatur ex consequat deserunt deserunt Ut aliqua Ut consectetur exercitation eiusmod eu in in do.Lorem ipsum Ex fugiat eiusmod Duis officia nulla incididunt aliquip minim officia incididunt aliquip do voluptate laboris Ut nostrud amet enim tempor.</p>
    </div>
  </div>
</div>
