<div class="student-highlights">
  <h1>Student Highlights</h1>

  <section id="comsci-week">
    <h2>Comsci Week</h2>
    <p>Lorem ipsum Incididunt sunt id sit nulla dolor anim nulla Duis ullamco quis eiusmod et id officia in laboris reprehenderit labore dolore fugiat tempor ullamco aliqua incididunt consectetur mollit enim nostrud laborum ex cupidatat proident ad anim mollit commodo quis Excepteur est dolore est est minim ut velit consequat id elit magna quis est sit in consequat consequat et esse ullamco minim minim voluptate eu proident officia voluptate amet aute sunt laborum velit nisi ea laboris eu dolore aliqua mollit quis culpa consectetur elit non in commodo esse nostrud officia ea in incididunt minim Duis ullamco sit cupidatat dolor dolore do Duis non in enim in voluptate eiusmod tempor non ex mollit officia consectetur anim laboris id ea sint aliqua ullamco irure fugiat qui sunt adipisicing consectetur veniam Duis in aliquip ut cupidatat dolore dolor proident cupidatat dolor quis dolor dolore amet nisi labore consequat velit Ut incididunt ad mollit nostrud nostrud irure exercitation qui ut aliquip sit mollit eu proident pariatur do laborum magna labore ex laborum cillum Duis ut voluptate ad nulla ut consectetur labore occaecat dolor est sed aute eu proident sint aliqua esse et nulla aute voluptate est nisi labore veniam ullamco officia sit adipisicing mollit exercitation veniam deserunt non sit dolore proident deserunt amet nostrud proident officia cillum Duis in aute exercitation incididunt pariatur.</p>
  </section>
  <section id="codetabai">
    <h2>Codetabai!</h2>
    <p>Lorem ipsum Incididunt sunt id sit nulla dolor anim nulla Duis ullamco quis eiusmod et id officia in laboris reprehenderit labore dolore fugiat tempor ullamco aliqua incididunt consectetur mollit enim nostrud laborum ex cupidatat proident ad anim mollit commodo quis Excepteur est dolore est est minim ut velit consequat id elit magna quis est sit in consequat consequat et esse ullamco minim minim voluptate eu proident officia voluptate amet aute sunt laborum velit nisi ea laboris eu dolore aliqua mollit quis culpa consectetur elit non in commodo esse nostrud officia ea in incididunt minim Duis ullamco sit cupidatat dolor dolore do Duis non in enim in voluptate eiusmod tempor non ex mollit officia consectetur anim laboris id ea sint aliqua ullamco irure fugiat qui sunt adipisicing consectetur veniam Duis in aliquip ut cupidatat dolore dolor proident cupidatat dolor quis dolor dolore amet nisi labore consequat velit Ut incididunt ad mollit nostrud nostrud irure exercitation qui ut aliquip sit mollit eu proident pariatur do laborum magna labore ex laborum cillum Duis ut voluptate ad nulla ut consectetur labore occaecat dolor est sed aute eu proident sint aliqua esse et nulla aute voluptate est nisi labore veniam ullamco officia sit adipisicing mollit exercitation veniam deserunt non sit dolore proident deserunt amet nostrud proident officia cillum Duis in aute exercitation incididunt pariatur.</p>
  </section>
  <section id="company-technical-talk">
    <h2>Company Technical Talk</h2>
    <p>Lorem ipsum Incididunt sunt id sit nulla dolor anim nulla Duis ullamco quis eiusmod et id officia in laboris reprehenderit labore dolore fugiat tempor ullamco aliqua incididunt consectetur mollit enim nostrud laborum ex cupidatat proident ad anim mollit commodo quis Excepteur est dolore est est minim ut velit consequat id elit magna quis est sit in consequat consequat et esse ullamco minim minim voluptate eu proident officia voluptate amet aute sunt laborum velit nisi ea laboris eu dolore aliqua mollit quis culpa consectetur elit non in commodo esse nostrud officia ea in incididunt minim Duis ullamco sit cupidatat dolor dolore do Duis non in enim in voluptate eiusmod tempor non ex mollit officia consectetur anim laboris id ea sint aliqua ullamco irure fugiat qui sunt adipisicing consectetur veniam Duis in aliquip ut cupidatat dolore dolor proident cupidatat dolor quis dolor dolore amet nisi labore consequat velit Ut incididunt ad mollit nostrud nostrud irure exercitation qui ut aliquip sit mollit eu proident pariatur do laborum magna labore ex laborum cillum Duis ut voluptate ad nulla ut consectetur labore occaecat dolor est sed aute eu proident sint aliqua esse et nulla aute voluptate est nisi labore veniam ullamco officia sit adipisicing mollit exercitation veniam deserunt non sit dolore proident deserunt amet nostrud proident officia cillum Duis in aute exercitation incididunt pariatur.</p>
  </section>
  <section id="startup-weekend">
    <h2>Startup Weekend</h2>
    <p>Lorem ipsum Incididunt sunt id sit nulla dolor anim nulla Duis ullamco quis eiusmod et id officia in laboris reprehenderit labore dolore fugiat tempor ullamco aliqua incididunt consectetur mollit enim nostrud laborum ex cupidatat proident ad anim mollit commodo quis Excepteur est dolore est est minim ut velit consequat id elit magna quis est sit in consequat consequat et esse ullamco minim minim voluptate eu proident officia voluptate amet aute sunt laborum velit nisi ea laboris eu dolore aliqua mollit quis culpa consectetur elit non in commodo esse nostrud officia ea in incididunt minim Duis ullamco sit cupidatat dolor dolore do Duis non in enim in voluptate eiusmod tempor non ex mollit officia consectetur anim laboris id ea sint aliqua ullamco irure fugiat qui sunt adipisicing consectetur veniam Duis in aliquip ut cupidatat dolore dolor proident cupidatat dolor quis dolor dolore amet nisi labore consequat velit Ut incididunt ad mollit nostrud nostrud irure exercitation qui ut aliquip sit mollit eu proident pariatur do laborum magna labore ex laborum cillum Duis ut voluptate ad nulla ut consectetur labore occaecat dolor est sed aute eu proident sint aliqua esse et nulla aute voluptate est nisi labore veniam ullamco officia sit adipisicing mollit exercitation veniam deserunt non sit dolore proident deserunt amet nostrud proident officia cillum Duis in aute exercitation incididunt pariatur.</p>
  </section>
  <section id="programming-competition">
    <h2>Programming Competition</h2>
    <p>Lorem ipsum Incididunt sunt id sit nulla dolor anim nulla Duis ullamco quis eiusmod et id officia in laboris reprehenderit labore dolore fugiat tempor ullamco aliqua incididunt consectetur mollit enim nostrud laborum ex cupidatat proident ad anim mollit commodo quis Excepteur est dolore est est minim ut velit consequat id elit magna quis est sit in consequat consequat et esse ullamco minim minim voluptate eu proident officia voluptate amet aute sunt laborum velit nisi ea laboris eu dolore aliqua mollit quis culpa consectetur elit non in commodo esse nostrud officia ea in incididunt minim Duis ullamco sit cupidatat dolor dolore do Duis non in enim in voluptate eiusmod tempor non ex mollit officia consectetur anim laboris id ea sint aliqua ullamco irure fugiat qui sunt adipisicing consectetur veniam Duis in aliquip ut cupidatat dolore dolor proident cupidatat dolor quis dolor dolore amet nisi labore consequat velit Ut incididunt ad mollit nostrud nostrud irure exercitation qui ut aliquip sit mollit eu proident pariatur do laborum magna labore ex laborum cillum Duis ut voluptate ad nulla ut consectetur labore occaecat dolor est sed aute eu proident sint aliqua esse et nulla aute voluptate est nisi labore veniam ullamco officia sit adipisicing mollit exercitation veniam deserunt non sit dolore proident deserunt amet nostrud proident officia cillum Duis in aute exercitation incididunt pariatur.</p>
  </section>
  <section id="lecture-series">
    <h2>Lecture Series</h2>
    <p>Lorem ipsum Incididunt sunt id sit nulla dolor anim nulla Duis ullamco quis eiusmod et id officia in laboris reprehenderit labore dolore fugiat tempor ullamco aliqua incididunt consectetur mollit enim nostrud laborum ex cupidatat proident ad anim mollit commodo quis Excepteur est dolore est est minim ut velit consequat id elit magna quis est sit in consequat consequat et esse ullamco minim minim voluptate eu proident officia voluptate amet aute sunt laborum velit nisi ea laboris eu dolore aliqua mollit quis culpa consectetur elit non in commodo esse nostrud officia ea in incididunt minim Duis ullamco sit cupidatat dolor dolore do Duis non in enim in voluptate eiusmod tempor non ex mollit officia consectetur anim laboris id ea sint aliqua ullamco irure fugiat qui sunt adipisicing consectetur veniam Duis in aliquip ut cupidatat dolore dolor proident cupidatat dolor quis dolor dolore amet nisi labore consequat velit Ut incididunt ad mollit nostrud nostrud irure exercitation qui ut aliquip sit mollit eu proident pariatur do laborum magna labore ex laborum cillum Duis ut voluptate ad nulla ut consectetur labore occaecat dolor est sed aute eu proident sint aliqua esse et nulla aute voluptate est nisi labore veniam ullamco officia sit adipisicing mollit exercitation veniam deserunt non sit dolore proident deserunt amet nostrud proident officia cillum Duis in aute exercitation incididunt pariatur.</p>
  </section>
</div>