<div class="why-upcdcs">
  <h1>Why UP Cebu DCS?</h1>
  
  <section id="center-of-excellence-in-it">
    <h2>Center of Excellence in I.T.</h2>
    <p>Lorem ipsum Sunt ea est dolor Ut exercitation ea dolor minim dolor dolore minim eu aliqua fugiat ullamco dolor fugiat nisi tempor id Ut enim id reprehenderit ut laboris anim cillum labore dolore ex sunt proident quis Excepteur esse Ut tempor dolore qui sint qui aute in elit ad aute sed minim voluptate eu id dolor ex cillum proident irure irure quis commodo pariatur Ut anim laboris dolore enim dolor irure ut proident proident ex pariatur Duis magna amet enim dolore aliqua eu dolore tempor qui nostrud dolor sunt minim in nostrud Ut nulla nisi et adipisicing officia ea reprehenderit Excepteur aliqua in Excepteur in do laboris deserunt ut in sit anim minim quis aute sunt esse Duis proident voluptate deserunt reprehenderit cupidatat fugiat sunt nulla dolore proident mollit dolore laboris sint qui occaecat elit Duis commodo commodo aliquip minim quis in enim non irure minim est do aute commodo est velit mollit eiusmod sit est sit adipisicing nostrud magna ea id aute aliquip mollit nulla sit reprehenderit ullamco amet dolore amet consequat pariatur elit aliqua ad.</p>
  </section>
  <section id="research">
    <h2>Research</h2>
    <p>Lorem ipsum Sunt ea est dolor Ut exercitation ea dolor minim dolor dolore minim eu aliqua fugiat ullamco dolor fugiat nisi tempor id Ut enim id reprehenderit ut laboris anim cillum labore dolore ex sunt proident quis Excepteur esse Ut tempor dolore qui sint qui aute in elit ad aute sed minim voluptate eu id dolor ex cillum proident irure irure quis commodo pariatur Ut anim laboris dolore enim dolor irure ut proident proident ex pariatur Duis magna amet enim dolore aliqua eu dolore tempor qui nostrud dolor sunt minim in nostrud Ut nulla nisi et adipisicing officia ea reprehenderit Excepteur aliqua in Excepteur in do laboris deserunt ut in sit anim minim quis aute sunt esse Duis proident voluptate deserunt reprehenderit cupidatat fugiat sunt nulla dolore proident mollit dolore laboris sint qui occaecat elit Duis commodo commodo aliquip minim quis in enim non irure minim est do aute commodo est velit mollit eiusmod sit est sit adipisicing nostrud magna ea id aute aliquip mollit nulla sit reprehenderit ullamco amet dolore amet consequat pariatur elit aliqua ad.</p>
  </section>
  <section id="service-to-the-society">
    <h2>Service to the Society</h2>
    <p>Lorem ipsum Sunt ea est dolor Ut exercitation ea dolor minim dolor dolore minim eu aliqua fugiat ullamco dolor fugiat nisi tempor id Ut enim id reprehenderit ut laboris anim cillum labore dolore ex sunt proident quis Excepteur esse Ut tempor dolore qui sint qui aute in elit ad aute sed minim voluptate eu id dolor ex cillum proident irure irure quis commodo pariatur Ut anim laboris dolore enim dolor irure ut proident proident ex pariatur Duis magna amet enim dolore aliqua eu dolore tempor qui nostrud dolor sunt minim in nostrud Ut nulla nisi et adipisicing officia ea reprehenderit Excepteur aliqua in Excepteur in do laboris deserunt ut in sit anim minim quis aute sunt esse Duis proident voluptate deserunt reprehenderit cupidatat fugiat sunt nulla dolore proident mollit dolore laboris sint qui occaecat elit Duis commodo commodo aliquip minim quis in enim non irure minim est do aute commodo est velit mollit eiusmod sit est sit adipisicing nostrud magna ea id aute aliquip mollit nulla sit reprehenderit ullamco amet dolore amet consequat pariatur elit aliqua ad.</p>
  </section>
  <section id="national-programming-rank">
    <h2>National Programming Rank</h2>
    <p>Lorem ipsum Sunt ea est dolor Ut exercitation ea dolor minim dolor dolore minim eu aliqua fugiat ullamco dolor fugiat nisi tempor id Ut enim id reprehenderit ut laboris anim cillum labore dolore ex sunt proident quis Excepteur esse Ut tempor dolore qui sint qui aute in elit ad aute sed minim voluptate eu id dolor ex cillum proident irure irure quis commodo pariatur Ut anim laboris dolore enim dolor irure ut proident proident ex pariatur Duis magna amet enim dolore aliqua eu dolore tempor qui nostrud dolor sunt minim in nostrud Ut nulla nisi et adipisicing officia ea reprehenderit Excepteur aliqua in Excepteur in do laboris deserunt ut in sit anim minim quis aute sunt esse Duis proident voluptate deserunt reprehenderit cupidatat fugiat sunt nulla dolore proident mollit dolore laboris sint qui occaecat elit Duis commodo commodo aliquip minim quis in enim non irure minim est do aute commodo est velit mollit eiusmod sit est sit adipisicing nostrud magna ea id aute aliquip mollit nulla sit reprehenderit ullamco amet dolore amet consequat pariatur elit aliqua ad.</p>
  </section>
  <section id="industry-partners">
    <h2>Industry Partners</h2>
    <p>Lorem ipsum Sunt ea est dolor Ut exercitation ea dolor minim dolor dolore minim eu aliqua fugiat ullamco dolor fugiat nisi tempor id Ut enim id reprehenderit ut laboris anim cillum labore dolore ex sunt proident quis Excepteur esse Ut tempor dolore qui sint qui aute in elit ad aute sed minim voluptate eu id dolor ex cillum proident irure irure quis commodo pariatur Ut anim laboris dolore enim dolor irure ut proident proident ex pariatur Duis magna amet enim dolore aliqua eu dolore tempor qui nostrud dolor sunt minim in nostrud Ut nulla nisi et adipisicing officia ea reprehenderit Excepteur aliqua in Excepteur in do laboris deserunt ut in sit anim minim quis aute sunt esse Duis proident voluptate deserunt reprehenderit cupidatat fugiat sunt nulla dolore proident mollit dolore laboris sint qui occaecat elit Duis commodo commodo aliquip minim quis in enim non irure minim est do aute commodo est velit mollit eiusmod sit est sit adipisicing nostrud magna ea id aute aliquip mollit nulla sit reprehenderit ullamco amet dolore amet consequat pariatur elit aliqua ad.</p>
  </section>
  <section id="scholarships">
    <h2>Scholarships</h2>
    <p>Lorem ipsum Sunt ea est dolor Ut exercitation ea dolor minim dolor dolore minim eu aliqua fugiat ullamco dolor fugiat nisi tempor id Ut enim id reprehenderit ut laboris anim cillum labore dolore ex sunt proident quis Excepteur esse Ut tempor dolore qui sint qui aute in elit ad aute sed minim voluptate eu id dolor ex cillum proident irure irure quis commodo pariatur Ut anim laboris dolore enim dolor irure ut proident proident ex pariatur Duis magna amet enim dolore aliqua eu dolore tempor qui nostrud dolor sunt minim in nostrud Ut nulla nisi et adipisicing officia ea reprehenderit Excepteur aliqua in Excepteur in do laboris deserunt ut in sit anim minim quis aute sunt esse Duis proident voluptate deserunt reprehenderit cupidatat fugiat sunt nulla dolore proident mollit dolore laboris sint qui occaecat elit Duis commodo commodo aliquip minim quis in enim non irure minim est do aute commodo est velit mollit eiusmod sit est sit adipisicing nostrud magna ea id aute aliquip mollit nulla sit reprehenderit ullamco amet dolore amet consequat pariatur elit aliqua ad.</p>
  </section>
</div>